"""ZeonmkII XY Plot — server routes (the /zeonmkii/api/xy_plot/* family).

Port of Pixaroma's XY Plot routes (server_routes.py, MIT): Save Output
(re-assemble the grid at the chosen Save resolution and write it + optionally
each cell into output/), Save Disk (render_full: PNG bytes for the browser's
download), and the instant theme Restyle. All of them rebuild from the cells
cached server-side by the node - no workflow re-run, no GPU work.
"""
import io
import os
import re

import folder_paths
from aiohttp import web
from server import PromptServer

from .xy_plot import render_session_full, resolve_save_cap, restyle_session, snapshot_session_cells

# ── guards ──────────────────────────────────────────────────────────────────

# Session ids are generated by the frontend (UUID-ish); a stricter charset than
# Pixaroma's because ours only ever sees one generator. Bounded so the id can't
# be used to balloon a temp filename.
_SAFE_ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")
_MAX_ID_LEN = 80


def _is_path_under(path, *roots):
    """Containment that survives symlinks: realpath both sides."""
    try:
        rp = os.path.realpath(path)
    except Exception:
        return False
    for root in roots:
        try:
            if os.path.commonpath([rp, os.path.realpath(root)]) == os.path.realpath(root):
                return True
        except ValueError:
            continue
    return False


def _safe_prefix(raw):
    """Sanitize a filename_prefix from the client. Keeps '/' (subfolders are
    resolved against output/ by folder_paths itself); anything else exotic
    becomes '_'. Returns "" for garbage, which the caller replaces with the
    default stem."""
    if not isinstance(raw, str):
        return ""
    cleaned = re.sub(r"[^A-Za-z0-9 _\-/]+", "_", raw.strip())
    return cleaned[:160]


@PromptServer.instance.routes.post("/zeonmkii/api/xy_plot/save")
async def api_xy_plot_save(request):
    """Save an XY Plot grid (already written to temp/ during the plot) to
    output/ with embedded workflow metadata. Optionally also write each
    individual cell into a <name>_cells/ subfolder.

    Request JSON: {
        grid_filename:   temp PNG filename of the assembled grid (required),
        session_id:      plot session id (only needed for save_cells),
        filename_prefix: output stem (default "xy_plot"),
        save_cells:      bool - also write each cell image,
        save_max_size:   "2048"|"4096"|"8192"|"full" Save resolution,
        workflow/prompt: optional metadata to embed in the grid PNG,
    }
    Response JSON: { status, filename, subfolder, saved_cells } or { error }.
    """
    from PIL.PngImagePlugin import PngInfo
    from .xy_plot import _build_pnginfo, _json_safe

    try:
        data = await request.json()
    except Exception:
        return web.json_response({"error": "invalid JSON"}, status=400)

    if not isinstance(data, dict):
        data = {}
    grid_filename = data.get("grid_filename")
    if not isinstance(grid_filename, str) or not grid_filename:
        return web.json_response({"error": "missing grid_filename"}, status=400)
    session_id = data.get("session_id")
    save_cells = data.get("save_cells") is True
    workflow = data.get("workflow")
    prompt = data.get("prompt")
    prefix = _safe_prefix(data.get("filename_prefix", "xy_plot")) or "xy_plot"

    valid_sid = isinstance(session_id, str) and bool(_SAFE_ID_RE.match(session_id)) and len(session_id) <= _MAX_ID_LEN

    # Prefer a grid re-assembled from the live session's cached cells at the
    # user's chosen Save resolution (built once, only on Save - the preview and
    # the IMAGE output stay capped at 4096). Falls back to the pre-rendered
    # (4096-capped) temp PNG when the session has been evicted or on any error.
    grid_pil = None
    if valid_sid:
        try:
            grid_pil = render_session_full(session_id, resolve_save_cap(data.get("save_max_size")))
        except Exception as e:
            print(f"[ZeonmkII] XY Plot: full-res re-assembly failed, using preview: {e}")
            grid_pil = None

    if grid_pil is None:
        temp_dir = folder_paths.get_temp_directory()
        safe_name = os.path.basename(grid_filename)
        grid_path = os.path.join(temp_dir, safe_name)
        if not safe_name or not os.path.isfile(grid_path) or not _is_path_under(grid_path, temp_dir):
            return web.json_response({"error": "grid image not found - re-run the plot, then Save"}, status=400)
        try:
            from PIL import Image
            grid_pil = Image.open(grid_path).convert("RGB")
        except Exception as e:
            return web.json_response({"error": f"could not read grid: {e}"}, status=500)

    try:
        output_dir = folder_paths.get_output_directory()
        full_folder, name, counter, subfolder, _ = folder_paths.get_save_image_path(
            prefix, output_dir, grid_pil.width, grid_pil.height
        )
        os.makedirs(full_folder, exist_ok=True)
        fname = f"{name}_{counter:05}_.png"
        pnginfo = _build_pnginfo(prompt=prompt, workflow=workflow)
        grid_pil.save(os.path.join(full_folder, fname), "PNG", pnginfo=pnginfo)
    except Exception as e:
        return web.json_response({"error": f"save failed: {e}"}, status=500)

    saved_cells = 0
    # Only attempt cells when explicitly requested AND the session id is a
    # valid, bounded token (valid_sid computed above; it keys an in-memory dict).
    if save_cells and valid_sid:
        try:
            cells, _gn = snapshot_session_cells(session_id)   # copied under the node's lock
            if cells:
                # Include the grid's counter in the folder name so saving the
                # same plot twice doesn't overwrite the first save's cells.
                cells_folder = os.path.join(full_folder, f"{name}_{counter:05}_cells")
                # Defense-in-depth: never write the cells subfolder outside output/.
                if _is_path_under(cells_folder, output_dir) or _is_path_under(os.path.dirname(cells_folder), output_dir):
                    os.makedirs(cells_folder, exist_ok=True)
                    for (xi, yi), cell in cells:
                        cell_name = f"{name}_x{xi}_y{yi}.png"
                        try:
                            cell.convert("RGB").save(os.path.join(cells_folder, cell_name), "PNG")
                            saved_cells += 1
                        except Exception:
                            pass
        except Exception as e:
            print(f"[ZeonmkII] XY Plot: save cells failed: {e}")

    return web.json_response({
        "status": "success",
        "filename": fname,
        "subfolder": subfolder,
        "saved_cells": saved_cells,
        "width": grid_pil.width,
        "height": grid_pil.height,
    })


@PromptServer.instance.routes.post("/zeonmkii/api/xy_plot/render_full")
async def api_xy_plot_render_full(request):
    """Return the XY Plot grid re-assembled at the requested resolution as PNG
    bytes, for the browser's Save Disk button (which downloads to the user's
    computer). Built once, on demand, from the cells cached server-side - the
    workflow/prompt are embedded so the downloaded PNG can be dragged back in.

    Request JSON: {
        session_id:      plot session id (required),
        save_max_size:   "2048"|"4096"|"8192"|"full" (default 4096),
        workflow/prompt: optional metadata to embed,
    }
    Response: image/png bytes, or JSON { error } (404 when the session expired,
    so the browser can fall back to the capped preview file).
    """
    from PIL.PngImagePlugin import PngInfo  # noqa: F401 - kept for parity with the save route
    from .xy_plot import _build_pnginfo

    try:
        data = await request.json()
    except Exception:
        return web.json_response({"error": "invalid JSON"}, status=400)
    if not isinstance(data, dict):
        data = {}
    session_id = data.get("session_id")
    if not isinstance(session_id, str) or not _SAFE_ID_RE.match(session_id) or len(session_id) > _MAX_ID_LEN:
        return web.json_response({"error": "invalid session id"}, status=400)
    workflow = data.get("workflow")
    prompt = data.get("prompt")
    try:
        grid_pil = render_session_full(session_id, resolve_save_cap(data.get("save_max_size")))
    except Exception as e:
        return web.json_response({"error": f"render failed: {e}"}, status=500)
    if grid_pil is None:
        return web.json_response({"error": "session expired - run the plot again"}, status=404)
    try:
        buf = io.BytesIO()
        grid_pil.save(buf, "PNG", pnginfo=_build_pnginfo(prompt=prompt, workflow=workflow))
    except Exception as e:
        return web.json_response({"error": f"encode failed: {e}"}, status=500)
    return web.Response(body=buf.getvalue(), content_type="image/png")


@PromptServer.instance.routes.post("/zeonmkii/api/xy_plot/restyle")
async def api_xy_plot_restyle(request):
    """Re-render the current XY Plot grid with a new color theme, without
    re-running the workflow (the cells are cached server-side). Used for the
    instant Grid theme switch.

    Request JSON: { session_id: str, theme: "dark"|"light"|"mono" }
    Response JSON: { status, filename } or { error } (404 if session expired).
    """
    try:
        data = await request.json()
    except Exception:
        return web.json_response({"error": "invalid JSON"}, status=400)
    if not isinstance(data, dict):
        data = {}
    session_id = data.get("session_id")
    theme = data.get("theme") or "dark"
    if not isinstance(session_id, str) or not _SAFE_ID_RE.match(session_id) or len(session_id) > _MAX_ID_LEN:
        return web.json_response({"error": "invalid session id"}, status=400)
    if theme not in ("dark", "light", "mono"):
        return web.json_response({"error": "invalid theme"}, status=400)
    try:
        name = restyle_session(session_id, theme)
    except Exception as e:
        return web.json_response({"error": f"restyle failed: {e}"}, status=500)
    if not name:
        return web.json_response({"error": "session expired - run the plot again"}, status=404)
    return web.json_response({"status": "success", "filename": name})
